# Generated by Django 3.2.5 on 2021-07-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_email',
            field=models.CharField(max_length=200),
        ),
    ]
